### PR TITLE
Draft/style shuffle

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
- buttons are still visible but disable instead and have different colors
- comment box is still visible but disabled instead
- terminal view should expand to not have it's own scrollbar
- result color for whole footer
- label in perspective widget should not shrink toggle button and indicator label

### CODE REVIEW

**Comment by mkolar** [comment]
Please move the stop button all the way to the left. When testing, we keep trying to click it as if it was play. Other than that. it's nice.

**Comment by mkolar** [comment]
We've got a small confict. Please fix, but other than that it's ready for merge

**Comment by mkolar** [comment]
actually I found a small issue.
 if collection fails, it only presents `refresh` which is correct, however if user then triggers an instance on the left (on or off), `validate` and `publish` become available again, which is dangerous, to say the least :)
Screenshot_8 
Screenshot_9

**Comment by iLLiCiTiT** [comment]
Cool bug ＼(◑д◐)＞∠(◑д◐)

**Review by mkolar — APPROVED** [review]

**Pull request merged**
